#!/bin/bash

ln -s ~/.dotfiles/alacritty/ ~/.config/alacritty
ln -s ~/.dotfiles/neovim/ ~/.config/nvim
ln -s ~/.dotfiles/starship/ ~/.config/starship
ln -s ~/.dotfiles/tmux/ ~/.config/tmux
ln -s ~/.dotfiles/zsh/zshrc ~/.zshrc
ln -s ~/.dotfiles/git/gitconfig ~/.gitconfig

