# Load Starship
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
eval "$(starship init zsh)"

export PATH=$HOME/.local/bin:/opt/rocm/bin:$PATH

# Fake 6700XT for compatibility since gx1031 is not supported
#export HSA_OVERRIDE_GFX_VERSION=10.3.0
#ROCM_PATH=""
#HIP_PATH="/usr/share/hip"
# Adding rocm binaries to path
#export PATH="$PATH":"$HIP_PATH"

# Activate Vi-Mode. zsh-vi-mode does not override
#set -o vi

export DOTFILES_ZSH="$HOME/.dotfiles/zsh"
# Clone Antidote[Plugin Manager] and load plugins
[[ -d ${DOTFILES_ZSH}/antidote ]] ||
    git clone --depth=1 https://github.com/mattmc3/antidote.git ${DOTFILES_ZSH}/antidote
source ${DOTFILES_ZSH}/antidote/antidote.zsh
antidote load ${DOTFILES_ZSH}/plugins.txt

HISTSIZE=1000000
HISTFILE=$DOTFILES_ZSH/zsh_history
SAVEHIST=1000000
source $DOTFILES_ZSH/zsh_aliases

setopt appendhistory
setopt share_history
setopt hist_ignore_all_dups
setopt hist_ignore_space
